### PR TITLE
Hide premium if unavailable

### PR DESCRIPTION
**Pull request by Vinnl**
This builds on #1374.

It hides references to Premium in countries where Premium is not available. It also replaces the hero image with a screenshot of non-Premium Relay, ~~but that's currently a bit distorted because I couldn't figure out how to properly export that from Figma and thus had to manually rescale it with the naked eye. I've asked Eduardo for help, so if he can tell me how to do it properly I'll add a properly-scaled image~~ Eduardo fixed it for me :)

As a bit of cleanup, I also removed the old homepage (in d4313a4c973355ad4b9c03e8e78da983d91e53e4).

### CODE REVIEW

**Comment by groovecoder** [comment]
I'm afraid I updated #1374 in a way that conflicts with this. 😢

**Comment by Vinnl** [comment]
No worries, it was still API-compatible, so I could rebase without conflicts. I did find a bug there (I think), but I've set this PRs target branch to your branch now, so that shouldn't be a problem.

**Review by maxxcrawford — COMMENTED** [review]
I'm not able to test this. Can you include directions? Do I need to change my default language/set VPN/etc? 

I turned off my VPN, set default language to English and was unable to get the premium upgrade prompts on the homepage. 

LMK!

**Comment by Vinnl** [comment]
@maxxcrawford Ah, that you don't get a Premium notice is probably a result of [this error](https://github.com/mozilla/fx-private-relay/pull/1374/files#r754193538) in #1374 - if you apply the change I suggested there, you should get it.

To test whether you _don't_ get the Premium notice, you can set your locale to a country's that doesn't have Premium, I think - it first looks for a request header that FxA adds, and lacking that (i.e. locally), it looks at your `Accept-Language` request header.

**Review by maxxcrawford — COMMENTED** [review]
I applied the change – I'm able to get the premium prompts to show when they should. I'm still not able to trigger the alternate (not available) now. 

(Set first language as Romania, VPN set to Romania) 

Could you please write out some concrete testing steps to reproduce?

**Comment by Vinnl** [comment]
Ah yes, there appears to be another bug: https://github.com/mozilla/fx-private-relay/pull/1374/files#r758728591

The way I tested it was by just setting `premium_available_in_country` to `True` or `False` in `utils.py` line 10.

**Comment by maxxcrawford** [comment]
> Ah yes, there appears to be another bug: https://github.com/mozilla/fx-private-relay/pull/1374/files#r758728591
> 
> The way I tested it was by just setting `premium_available_in_country` to `True` or `False` in `utils.py` line 10.

Works for me – I'll re-review. :)

**Comment by groovecoder** [comment]
I fixed the bug in https://github.com/mozilla/fx-private-relay/pull/1374/files#r758728591.

**Review by maxxcrawford — APPROVED** [review]
Good to go (esp. since it's merging into the other PR). Nice clean up on the templates too!

**Comment by Vinnl** [comment]
Great, rebased on top of that branch. @groovecoder feel free to merge this into your branch if you want, or merge yours first and then I can merge this into `main` too :)

**Comment by groovecoder** [comment]
This has conflicts now that I updated https://github.com/mozilla/fx-private-relay/pull/1374.

**Comment by Vinnl** [comment]
Rebasing now.

**Comment by groovecoder** [comment]
Code looks good and spot-checks work.

1. Language `en-US`: see the upgrade buttons with plan ID matching US
2. Language `en-au`: did *NOT* see the upgrade buttons
   * *until* I modified the request to set `X-Client-Region: us`, and then I *DID* see the upgrade buttons.
3. Language `en-US`, `X-Client-Region: nl`: see the upgrade buttons with plan ID matching NL

**Pull request merged**
