### PR TITLE
MPP-3239: Removed custom domain tooltip 

### PR DESCRIPTION
**Pull request by rafeerahman**
This PR fixes MPP-3239.
 

# New feature description

Removed the tooltip that appears when clicking your custom domain.

# Screenshot (if applicable)

# How to test
Click the domain next to "Your Relay email domain". The expected behaviour is that nothing happens, and no tool-tip shows up.

# Checklist (Definition of Done)
- [x] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [x] All acceptance criteria are met.
- [x] Jira ticket has been updated (if needed) to match changes made during the development process.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [x] l10n changes have been submitted to the l10n repository, if any.

### CODE REVIEW

**Review by lloan — APPROVED** [review]
Tested and it works as expected. Thanks!

**Comment by rafeerahman** [comment]
Waiting for L10 repo permissions before I merge to remove the strings that were deleted.

**Comment by Vinnl** [comment]
Sorry for jumping in @rafeerahman, but it's safest to _first_ merge the code changes and only after remove the strings. Unused strings aren't really a problem, but references to non-existent strings will result in `???` being visible in the UI.

(Unused strings aren't a problem in that they won't show up for users. They'll still be listed as localisable for our volunteer localisers, so to avoid superfluous work for them, it's still best to remove them afterwards.)

**Comment by rafeerahman** [comment]
> 

Thanks for jumping in, was curious about that as well. How does this go when making updates to strings? I'm assuming we would want to merge the code changes with pendingTranslations first, and then merge the PR we would have made to update the strings in l10 (following https://github.com/mozilla-l10n/documentation/blob/main/src/localization/dev_best_practices.md#fluent-files)

**Comment by Vinnl** [comment]
See Peiying's comment [here](https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/153#pullrequestreview-1550757506), but the tl;dr is that you add new strings (rather than updating existing strings - the translators won't get notifications about changed strings) with e.g. a `-2` suffix. By adding them to `pendingTranslations.ftl`, you can already merge your code to make sure that at least the English text shows up.

You can then submit those new strings in a PR to the l10n repository, and add

```
# Deprecated
```

to the old strings. (And every now and then submit a PR that removes all strings marked as deprecated.) Once that PR gets merged to the l10n repository, it will eventually automatically be included in this repository as well, but you don't need to do anything to make that happen.

So the process is:

1. Submit PR with code changes and new strings in `pendingTranslations.ftl`. Wait for review, meanwhile:
2. Submit PR with new strings to the l10n repository. Wait for review.

Those can then be merged whenever they're approved in either order. Just make sure the deprecated strings aren't removed before the new strings are in production.

**Pull request merged**
