### PR TITLE
Fix ga events mpp 3422

### PR DESCRIPTION
**Pull request by groovecoder**
This PR fixes #MPP-3422.

How to test:
1. Open developer tools to the 'Console' panel
2. Go to http://127.0.0.1:8000/accounts/profile/
3. Click on as many "upsell" buttons you can (they usually say "Upgrade" but look around to see if you see any more)
   * [ ] Check the 'Console' panel for GA events. They should have `eventCategory: "Purchase ___"`
4. Go to 127.0.0.1:8000/premium/#pricing (many of the previous "Upgrade" links will take you here
5. Click on as many purchase buttons you can (they usually say "Upgrade" but look around to see if you see any more)
   * [ ] Check the 'Console' panel for GA events. They should have `eventCategory: "Purchase ___"`
6. Go to http://127.0.0.1:8000/phone/
7. Click on as many "upsell" buttons you can (they usually say "Upgrade" but look around to see if you see any more)
   * [ ] Check the 'Console' panel for GA events. They should have `eventCategory: "Purchase ___"`

- [x] ~l10n changes have been submitted to the l10n repository, if any.~
- [x] ~I've added a unit test to test for potential regressions of this bug.~
- [x] ~I've added or updated relevant docs in the docs/ directory.~
- [x] ~All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).~
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Comment by rafeerahman** [comment]
/accounts/profile
Clicking the upsell banner:
image
Clicking the Relay + VPN bundle banner:
image
Clicking the Phone upgrade banner:
image
Clicking the upgrade button at the bottom of profile banner:
image

(Possibly blocking?) Just to confirm, should these have an "engage" or "view" eventAction? 

/premium/#pricing
Monthly, yearly plans:
image
image
image
image

/phone
image
image

Everything seems to be working as intended. Looks good.

Question: Should opening in a new tab send a GA event as well? For example, right clicking the upgrade buttons then clicking "open in new tab". Or clicking the buttons with your scroll wheel. Currently only seeing the events when I left click the buttons.

**Review by lloan — APPROVED** [review]
Code looks good to me, very straightforward and the functionality is there: 
image

Thanks!

**Comment by rafeerahman** [comment]
**On accounts/profile, I see the "engage" event for these buttons:**

image
image

**I do not see the event for the following buttons:**

Upsell banner (when a free user reaches 5 masks):
Upsell banner (when a free user reaches 5 masks)

"Get your own domain" button:
image

Phone upgrade banner:
image

**Comment by groovecoder** [comment]
Okay, I think I got all those now too. Try again?

**Comment by rafeerahman** [comment]
> Okay, I think I got all those now too. Try again?

Confirmed they work now. 

{"hitType":"event","eventCategory":"Purchase button","eventAction":"Engage","eventLabel":"premium-promo-stop-spam"}
{"hitType":"event","eventCategory":"Purchase Button","eventAction":"Engage","eventLabel":"profile-set-custom-domain"}
{"hitType":"event","eventCategory":"Purchase Button","eventAction":"Engage","eventLabel":"upgrade-premium-header-mask-limit"}

I realized theres one more button that you might have missed, next to search masks.
image

**Comment by groovecoder** [comment]
Got it in abc97e88a1a5061cf85633c46c02ea1e49ef490f.

**Comment by rafeerahman** [comment]
> Got it in [abc97e8](https://github.com/mozilla/fx-private-relay/commit/abc97e88a1a5061cf85633c46c02ea1e49ef490f).

Looks good! 

Got the following: {"hitType":"event","eventCategory":"Purchase Button","eventAction":"Engage","eventLabel":"profile-create-alias-upgrade-promo"}

**Pull request merged**
