### PR TITLE
bump version to 1.4.7 to re-submit to AMO

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
I had to re-submit because I forgot to run `npm run build:prod`, so I accidentally submitted 1.4.6 with `127.0.0.1:8000` instead of `relay.firefox.com`.

**Comment by pdehaan** [comment]
[AMO already has a 1.4.7](https://addons.mozilla.org/en-US/firefox/addon/private-relay/versions/), I'm confused.
Unless you built locally and pushed to AMO before this PR, in which case makes total sense.

I'd also like to dig into what's the deal with https://github.com/mozilla/fx-private-relay/issues/104 before we do too many more pushes to AMO if we think we're bundling a bunch of dead files.
In fact, we might want to retool the build process a bit to remove some duplication and maybe build for prod by default to avoid future footguns.

**Review by pdehaan — APPROVED** [review]
1.4.7 is indeed higher than 1.4.6, so the numbers are trending correctly.

R+ 👍  :shipit: 🚢  🚀

**Comment by groovecoder** [comment]
I did build 1.4.7 locally and publish to AMO before merging this - so I could catch TheOne before they left for the weekend.

In my hurry to build 1.4.7 with the correct domain, I bad-pasted the commands from `npm run build:prod` into my CLI. In doing that, I accidentally changed `--ignore-files` to `--      ignore-files` which is why 1.4.7 got the hidden files this time.

Next time, `npm run build:prod` should correctly ignore the files.

**Pull request merged**
