### PR TITLE
MPP-3589 - Show news item only to free users

### PR DESCRIPTION
**Pull request by lloan**
This PR fixes MPP-3589 

How to test:

- [ ] l10n changes have been submitted to the l10n repository, if any.
- [ ] I've added a unit test to test for potential regressions of this bug.
- [ ] I've added or updated relevant docs in the docs/ directory.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

# New feature description

Show news item only to free users

# Screenshot (if applicable)

Not applicable.

# How to test

News item for Holiday Promo 2023 should appear only to free users. 

# Checklist (Definition of Done)
- [ ] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [ ] All acceptance criteria are met.
- [ ] Jira ticket has been updated (if needed) to match changes made during the development process.
- [ ] I've added or updated relevant docs in the docs/ directory
- [ ] Jira ticket has been updated (if needed) with suggestions for QA when this PR is deployed to stage.
- [ ] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [ ] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [ ] l10n changes have been submitted to the l10n repository, if any.

### CODE REVIEW

**Review by say-yawn — APPROVED** [review]
LGTM.

The [Figma for the dashboard](https://www.figma.com/file/nUvE6f4BWV5mugnynEJFnx/Relay-Pencil-Banner?type=design&node-id=57-2730&mode=design&t=V7FQAzkmDmVSX8ZF-4) indicates Free and signed-in users.
Also, the change is small and `profile.has_premium` has been used in the past.

**Comment by say-yawn** [comment]
Waiting on PM and Design input before finalizing.

**Review by rafeerahman — COMMENTED** [review]
Confirming that the news item is only showing for free users.

I noticed that the news item shows in the "news column" and in the "history" initially. Shouldn't it only show in the history once its dismissed?

**Comment by lloan** [comment]
> Confirming that the news item is only showing for free users.
> 
> I noticed that the news item shows in the "news column" and in the "history" initially. Shouldn't it only show in the history once its dismissed?

When you have dismissed it, it will always be in the history tab. You can remove the cookie related to that news item while testing.

**Comment by lloan** [comment]
Merging as [Doris confirmed the figma is correct ](https://mozilla.slack.com/archives/C013CSYEL5T/p1700703377447859?thread_ts=1700684030.190389&cid=C013CSYEL5T)

**Pull request merged**
