### PR TITLE
MPP-79: ADR 0004, Use Code Linters to Enforce Layout and Discover Issues

### PR DESCRIPTION
**Pull request by jwhitlock**
*Work in progress* - First draft complete. I'll revise tomorrow.

As suggested on https://github.com/mozilla/fx-private-relay/pull/3858#pullrequestreview-1611193596, this ADR addresses code linters on Relay, identifies a gap in linting for Python, and suggests `ruff` for filling that gap.

### CODE REVIEW

**Comment by jwhitlock** [comment]
Ready to review

**Review by groovecoder — APPROVED** [review]
Fantastic and thorough write-up. `ruff` sounds good.

**Review by say-yawn — APPROVED** [review]
Learned a lot more about when and how to choose a linter. Thanks for this helpful ADR, @jwhitlock. Recommendation to use `ruff` sounds good to me too.

**Comment by jwhitlock** [comment]
Thanks for the reviews! I'm updating the status then merging.

**Pull request merged**
