### PR TITLE
Truncate _very_ long domain names

### LINKED ISSUE #1091: Alias domain not fully visible in the confirmation dialog
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription but no email domain added.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in with an existing account.
2. Fill in the Search domain field and click the "Get Domain" button.
3. Observe the confirmation dialog.

**Actual result:**
The alias domain is not fully visible in the dialog.

**Expected result:**
The alias domain is fully visible in the dialog.

domain not fully visible in confirmationdialog

### PR DESCRIPTION
**Pull request by Vinnl**
Fixes #1091.

image

image

image

### CODE REVIEW

**Comment by groovecoder** [comment]
Hmm ... I expect these names would throw an error on the back-end too. It's strange that they're "available"

**Comment by Vinnl** [comment]
@groovecoder Isn't the limit 63 characters? Because that's still pretty long :)

```
> "hupseflupsebullekebupshajooojkslfjksld".length
38
```

**Review by maxxcrawford — APPROVED** [review]
I love me a CSS only fix! Nice work.

**Comment by maxxcrawford** [comment]
> Hmm ... I expect these names would throw an error on the back-end too. It's strange that they're "available"

Do we need to file a separate issue to adjust the length of a domain?

**Pull request merged**
