### PR TITLE
remove waitlist and invitations from back-end

### PR DESCRIPTION
**Pull request by groovecoder**
Just a draft pull request for now. This is a first pass at removing all of the wait-list and invitation code from the closed beta phase.

@lesleyjanenorton - will need/want you to remove the wait-list and invitation code from extension and site front-end.

### CODE REVIEW

**Comment by lesleyjanenorton** [comment]
@groovecoder yeah - when do we want to get this out?

**Comment by groovecoder** [comment]
Needs conflict resolution in `static/js/app.js`

**Comment by groovecoder** [comment]
I *think* I resolved the `app.js` conflict properly.

**Comment by lesleyjanenorton** [comment]
What does the error say/look like? I get this when setting up a new account locally
Screen Shot 2020-08-12 at 1 27 37 PM.

**Comment by groovecoder** [comment]
I got that at first, because I needed to run my db migration first. But on future sign-ups it seemed to work fine?

**Pull request merged**
