### PR TITLE
Improve scrolling experience across browsers

### LINKED ISSUE #3079: Blank areas when searching on mobile
I'm on Firefox on iOS. When trying to manage my relay emails the UI has this large (and changing size) white box which makes relay close to unusable.

### LINKED ISSUE #3223: Ensure that there is no white space underneath the footer for shorter pages
Screenshot from 2023-03-24 11-25-32

The fix for this was removed in https://github.com/mozilla/fx-private-relay/pull/3222, to fix [MPP-2920](https://mozilla-hub.atlassian.net/browse/MPP-2920), so make sure that doesn't regress when fixing this bug.

[MPP-2920]: https://mozilla-hub.atlassian.net/browse/MPP-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### LINKED ISSUE #3406: Inconsistent scrolling across browsers and screen sizes
The position of the banner and header when scrolling changes across different screen sizes as shown by the examples below. The scrolling in Chrome is also worse due to multiple scroll bars. This might be related to #3079.

I think the intended result would be to have the banner disapear from view when scrolling, while the header remains in view at the top of the screen.

Chrome:

bad-chrome-scroll

Firefox:

bad-firefox-scroll

### LINKED ISSUE #3407: Mobile menu does not stay under header when scrolling
As said in the title, the menu does not stay under header when scrolling. I would expect the menu to stay underneath the header and within view when scrolling.

Chrome:

Firefox:

### PR DESCRIPTION
**Pull request by joaonunomota**
This PR fixes #3407, fixes #3406, fixes #3223, fixes #3079.

Updates layout structure and styling to avoid the issues above. It also moves the menu for small/mobile screens inside the header so that it is able to scroll smoothly with the header.

How to test:

1. Go to Private Relay website (on iOS / Windows / Android browser).
2. Scroll through each page (including tracker report)
3. Observe the following:
   1. Short pages have the footer reach the bottom of the screen
   2. Mobile menu remains directly under the header during scrolling
   3. There are not multiple scroll bars on the page
   4. No blank areas while scrolling on mobile

- [ ] ~l10n changes have been submitted to the l10n repository, if any.~ (N/A)
- [ ] ~I've added a unit test to test for potential regressions of this bug.~ (N/A)
- [ ] ~I've added or updated relevant docs in the docs/ directory.~ (N/A)
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Comment by lloan** [comment]
I reviewed the changes and for the most part it looks great. Only issue I see at the moment is on mobile. The mobile menu isn't playing nice - see video for reference (sorry for loud video!). 

https://github.com/mozilla/fx-private-relay/assets/3924990/cbe8118c-2065-4795-b094-af492a4f15a5

**Review by lloan — CHANGES_REQUESTED** [review]
I reviewed the changes and for the most part it looks great. Only issue I see at the moment is on mobile. The mobile menu isn't playing nice - see video for reference (sorry for loud video!). 

https://github.com/mozilla/fx-private-relay/assets/3924990/cbe8118c-2065-4795-b094-af492a4f15a5

**Comment by joaonunomota** [comment]
> I reviewed the changes and for the most part it looks great. Only issue I see at the moment is on mobile. The mobile menu isn't playing nice - see video for reference (sorry for loud video!).

Thanks for the feedback! I updated the styling to allow scrolling within the navigation menu when it is too large for the screen.

I found no further issues testing in Chrome / Firefox on Windows 11 and Safari on iOS.

**Comment by jwhitlock** [comment]
Thanks @joaonunomota! I re-opened this on https://github.com/mozilla/fx-private-relay (You are listed as author, me as committer), and they've merged as PR #3652.

**Pull request closed without merging**
