### PR TITLE
add REDIS_CACHE_URL for caching and sessions

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Review by Micheletto — APPROVED** [review]
r+

**Review by say-yawn — APPROVED** [review]
LGTM.

**Comment by say-yawn** [comment]
Can we merge this?

**Comment by groovecoder** [comment]
Should be fine to merge, yes. It shouldn't do anything unless/until env vars are configured for it. I was keeping this open as a reminder that we haven't done this for stage + prod yet though.

**Comment by say-yawn** [comment]
@moz-astults Do you want to look at this and decide whether or not I should include this in the release request coming soon?

**Comment by moz-astults** [comment]
@say-yawn Taking a look and getting the access I need to make this happen.

**Pull request merged**
