### PR TITLE
Make the dashboard switcher non-sticky

### PR DESCRIPTION
**Pull request by Vinnl**
This PR (that targets #2390) tackles two things at once:

- Ensures the Duo Mobile Nav is not visible on the settings, FAQ and interstitial pages when the user is logged in
- Makes the Duo Mobile Nav non-sticky again, to preserve screen real estate on mobile (discussed with Eduardo)

@codemist This PR will merge into your PR, so up to you if you're OK with this approach, would like to try another one, or even want to push back on whether the changes are necessary in the first place :)

### CODE REVIEW

**Comment by codemist** [comment]
LGTM - but just wondering if the dashboard switcher (dig that name btw!) should stay sticky?

https://user-images.githubusercontent.com/13066134/187132117-5d41fc39-4034-42fb-bdf8-c548d2aec302.mov

**Comment by Vinnl** [comment]
@codemist Yeah, I discussed that with Eduardo, but it's taking up quite a bit of screen real estate, which is a scarce resource on small screens :) Ideally he'd have wanted it to show up sticky, but only when scrolling up, but I pushed back on that a bit because that's hard to do without negatively impacting performance (also a scarce resource on many mobile devices!), so he then said that non-sticky would be better:

image

(I brought it up separately from your PR because I didn't want to slow down that PR in case he didn't want it to change.)

**Comment by codemist** [comment]
@Vinnl Works for me - we should probably then distinguish between 'phone' and 'email' dashboards in the regular Mobile navigation.

**Review by codemist — APPROVED** [review]

**Comment by Vinnl** [comment]
@codemist Oh yeah, good point! And maybe

**Pull request merged**
