### PR TITLE
Content refresh

### LINKED ISSUE #1814: "Create a new alias" step on homepage not translated in the corresponding language
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
Browser's language is set to German/ French/ Dutch/ Italian, etc.

**Steps to reproduce:**

1. Navigate to Relay page.
2. Go to "How it works" section and observe the text for "Create a new alias" step.

**Actual result:**
The text is not translated in the corresponding language.

**Expected result:**
The text is translated in the corresponding language.

**Notes:**
N/A

no translation - german
no translation - french

### PR DESCRIPTION
**Pull request by Vinnl**
# New feature description

~~Do not merge this until after April 19th, so that localisers have time to deal with the unfortunate massive workload we're generating here :(~~

This applies three primary changes across the entire website:
- An "alias" is now called a "mask"
- A "real email" is now called a "true email"
- We're using "subdomain" consistently now, rather than "domain"

For that, it uses the strings from https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/66.

Fixes #1814.

# How to test

Check out https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/66, then verify that there's no mention of "alias", "real email" and "domain" anywhere anymore.

# Checklist

- [x] l10n dependencies have been merged, if any. Not yet: https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/66
- [x] All acceptance criteria are met.
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Comment by groovecoder** [comment]
Code- and spot-checks look good to me.

**Comment by Vinnl** [comment]
Rebased to resolve conflicts, and to fix up a couple more strings that I found (see https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/74 for the related l10n PR).

**Comment by groovecoder** [comment]
I wanna make sure @maxxcrawford or @codemist get a chance at this too.

**Review by maxxcrawford — APPROVED** [review]
So many IDs. 🕵️ 

Good to go!

**Pull request merged**
