### PR TITLE
Fix #898 - Update VPN promo banner copy

### LINKED ISSUE #898: Remove Mozilla VPN intro pricing banner on Relay: JULY 13th
Remove the mozilla vpn intro pricing on July 13th on Private Relay and replace with the following banner: https://www.figma.com/file/WN71ne5UZkkUsNdRjCnXP2/Monitor-VPN-Banner?node-id=0%3A1 

In relation to: https://github.com/mozilla/fx-private-relay/issues/897

### PR DESCRIPTION
**Pull request by maxxcrawford**
### ⚠️  **NOTE: DO NOT MERGE/DEPLOY UNTIL TUESDAY, JULY 13TH** ⚠️

This PR removes the current pricing promo from the VPN banner. The new strings match what is also on Monitor. 

**Note that because this app is not currently localized, this promo will appear to ALL USERS, only in English.** 

Preview: 
image

## Testing

- Clear any previous cookies for `mozgcp.net` if you have tested this this banner previously) 
- Go to homepage (https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/) 
- **Expected:** See VPN banner at top of the page with the following text: 
  - Headline: _Now’s the time to boost your safety online._
  - Body copy: _Mozilla’s Virtual Private Network helps shield your internet connection from hackers and spies._

### CODE REVIEW

**Comment by maxxcrawford** [comment]
cc/ @tcinotto

**Comment by maxxcrawford** [comment]
@lesleyjanenorton Use this URL to test (if you don't wanna run it locally): https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/

**Review by lesleyjanenorton — APPROVED** [review]
Thank you for the link! Looks great - only noticed one thing and it's the tiniest of nits: `.vpn-promo-banner button` (only the close button though) has the faintest background color and would probably benefit from`background: transparent;`. 
Screen Shot 2021-07-12 at 7 36 44 PM

**Comment by maxxcrawford** [comment]
@lesleyjanenorton Ahh! Great catch. Fixed!

**Pull request merged**
