### PR TITLE
Add the Credential Manager integration announcement

### PR DESCRIPTION
**Pull request by Vinnl**
# New feature description

This adds a news announcement about the integration with Credential Manager.

# Screenshot (if applicable)

See preview site.

# How to test

Set your computer clock to December 14th or later, then open the dashboard in Firefox. You should see the announcement.

# Checklist

- [x] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [x] All acceptance criteria are met. - Sort of, there's no mention of the icon being turned off, but we won't do it and it wasn't in the designs either.
- [ ] User Story has been updated (if needed) to match changes made during the development process. - I added one case: hiding the announcement if not using Firefox. Still need to get approval about that.
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] User Story has been updated (if needed) with suggestions for QA when this PR is deployed to stage.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [x] l10n changes have been submitted to the l10n repository, if any. - https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/115

### CODE REVIEW

**Review by lloan — APPROVED** [review]
Works as intended (was under news, then after viewing, goes into history) : 
image

**Comment by Vinnl** [comment]
Thanks! I also added 28770e49; the acceptance criteria were updated to a later announcement date to allow for Firefox's staged rollout. I still have an open question about it not being visible in other browsers.

**Comment by lloan** [comment]
> Thanks! I also added [28770e4](https://github.com/mozilla/fx-private-relay/commit/28770e49c9581b6d90cb286881d7ac74804a8a3c); the acceptance criteria were updated to a later announcement date to allow for Firefox's staged rollout. I still have an open question about it not being visible in other browsers.

Do you need me to do any additional testing on specific browsers?

**Comment by Vinnl** [comment]
@lloan Ah no sorry, the open question is for Tony to confirm that that behaviour is desirable. If so, I'll add it to the acceptance criteria and QA will do another check.

**Comment by Vinnl** [comment]
Actually, I'll just go ahead and merge this, as I assume it'll be fine. If not, I'll just submit a followup PR.

**Pull request merged**
