### PR TITLE
add full_address to address API responses

### PR DESCRIPTION
**Pull request by groovecoder**
# New feature description
This adds a new field to the `/api/v1/relayaddresses/` and `/api/v1/domainaddresses/` endpoints:
* `full_address`: shows the full address

# Screenshot (if applicable)
image

# How to test
* Go to http://127.0.0.1:8000/api/v1/relayaddresses/
   * [ ] Check that `full_address` values are accurate
* Go to http://127.0.0.1:8000/api/v1/domainaddresses/
   * [ ] Check that `full_address` values are accurate

# Checklist
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by say-yawn — CHANGES_REQUESTED** [review]
Would like `full_address` field to be on `read_only_fields` as well.

**Comment by Vinnl** [comment]
Oh nice, this is going to be useful in the front-end!

**Comment by groovecoder** [comment]
@say-yawn - Good catch, thanks. Updated.

@Vinnl agree. one of those quick suggestions @maxxcrawford made while he was in punching range of me. 😄

**Review by say-yawn — APPROVED** [review]
LGTM

**Pull request merged**
