### PR TITLE
Rectified issue #1046

### PR DESCRIPTION
**Pull request by oreo2107**
I wish to work on #1046 please assign this issue to me.

### CODE REVIEW

**Comment by oreo2107** [comment]
Issue #1046 is rectified. I tested and verified it on Firefox (Windows 10 and Ubuntu 20.04) and the visibility works successfully.
Approach:
- Stored the target div into **filterInputHandler**:

`const filterInputHandler = document.querySelector(".c-filter-search-controls");`

- Changed the visibility to **hidden** when search bar is empty:

`filterInputHandler.style.visibility = "hidden";`

- And changed the visibility to **visible** when search query exists in search bar:

`filterInputHandler.style.visibility = "visible";`

**Comment by groovecoder** [comment]
Hi, thanks for the contribution. It may take us a little bit to get to it, but we'll try to review soon.

**Comment by oreo2107** [comment]
Alright, thanks for acknowledging the contribution.

**Comment by maxxcrawford** [comment]
Hey there! This may PR may need to be revised, as #1082 will landing soon and refactors the Filtering system.

**Comment by Vinnl** [comment]
Aw I hadn't seen this, apologies - #1082 also fixes #1046, making this PR redundant. Sorry about that @oreo2107, thanks for your effort. I'm new on the team - going forward I should hopefully be more familiar with PRs already in progress.

**Pull request closed without merging**
