### PR TITLE
The Big One - rebased

### PR DESCRIPTION
**Pull request by Vinnl**
# New feature description

This is #1518, but rebased on `main`, so that conflicts are resolved, and in a new PR so the GitHub UI doesn't choke.

# How to test

See README.

# Checklist

- [ ] l10n dependencies have been merged, if any. - There's still a lot in `pendingTranslations.ttl` (mostly strings only visible to screen readers) that we'll need to merge there before making this public.
- [ ] All acceptance criteria are met. N/A
- [x] I've added or updated relevant docs in the docs/ directory.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/static/scss/libs/protocol/css/includes/tokens/dist/index.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by maxxcrawford — APPROVED** [review]
Already approved from #1518. Moving approval here too. :)

**Comment by groovecoder** [comment]
This looks good to me. The localhost:3000 sign-in is still really clunky. Could we add a field like `127_last_signed_in_user: <auth_token>` to the `runtime_data` endpoint when running in `DEBUG` mode (not on heroku)? That way, we could use 127.0.0.1:8000 to sign in, and then switch over to localhost:3000 for dev + debugging.

**Review by groovecoder — APPROVED** [review]

**Review by groovecoder — CHANGES_REQUESTED** [review]
Wait ... this says it's rebased, but I didn't see the "block promotional emails" UI when I went to my local dashboard?

**Comment by maxxcrawford** [comment]
> Wait ... this says it's rebased, but I didn't see the "block promotional emails" UI when I went to my local dashboard?

There's still a bunch of extra React features in flight, including that one: https://github.com/mozilla/fx-private-relay/pulls?q=is%3Apr+is%3Aopen+label%3Areact

**Review by groovecoder — APPROVED** [review]

**Comment by groovecoder** [comment]
Okay, worksforme.

**Comment by Vinnl** [comment]
Great, thanks both! I just updated all dependencies to the latest version (and verified that things still work); will merge when the build succeeds.

**Pull request merged**
