### PR TITLE
Stylelint updates

### PR DESCRIPTION
**Pull request by maxxcrawford**
Add additional rules for SCSS linting: 

- [rule-empty-line-before](https://stylelint.io/user-guide/rules/list/rule-empty-line-before)
- [no-missing-end-of-source-newline](https://stylelint.io/user-guide/rules/list/no-missing-end-of-source-newline)
- [rule-empty-line-before](https://stylelint.io/user-guide/rules/list/rule-empty-line-before)
- [declaration-colon-space-before](https://stylelint.io/user-guide/rules/list/declaration-colon-space-before)
- [declaration-colon-space-after](https://stylelint.io/user-guide/rules/list/declaration-colon-space-after)
- [block-closing-brace-newline-after](https://stylelint.io/user-guide/rules/list/block-closing-brace-newline-after)
- [block-opening-brace-newline-after](https://stylelint.io/user-guide/rules/list/block-opening-brace-newline-after)
- [at-rule-empty-line-before](https://stylelint.io/user-guide/rules/list/at-rule-empty-line-before)

### CODE REVIEW

**Review by codemist — APPROVED** [review]

**Comment by suicidemc** [comment]
> Add additional rules for SCSS linting:
> 
>     * [rule-empty-line-before](https://stylelint.io/user-guide/rules/list/rule-empty-line-before)
> 
>     * [no-missing-end-of-source-newline](https://stylelint.io/user-guide/rules/list/no-missing-end-of-source-newline)
> 
>     * [rule-empty-line-before](https://stylelint.io/user-guide/rules/list/rule-empty-line-before)
> 
>     * [declaration-colon-space-before](https://stylelint.io/user-guide/rules/list/declaration-colon-space-before)
> 
>     * [declaration-colon-space-after](https://stylelint.io/user-guide/rules/list/declaration-colon-space-after)
> 
>     * [block-closing-brace-newline-after](https://stylelint.io/user-guide/rules/list/block-closing-brace-newline-after)
> 
>     * [block-opening-brace-newline-after](https://stylelint.io/user-guide/rules/list/block-opening-brace-newline-after)
> 
>     * [at-rule-empty-line-before](https://stylelint.io/user-guide/rules/list/at-rule-empty-line-before)

NO SSA SSEWE

**Comment by suicidemc** [comment]
<details><summary>Details</summary>
<p>



WWEAWSR510650

</details>

**Comment by suicidemc** [comment]
/ #4587

**Comment by suicidemc** [comment]
1. [ ]

**Pull request merged**
