### PR TITLE
MPP-3261: New modal design for mask generation

### PR DESCRIPTION
**Pull request by rafeerahman**
This PR fixed MPP-3261.

- [x] l10n changes have been submitted to the l10n repository, if any. _(Should I do this after the PR is approved?)_
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

# New feature description

Redesigned the "Generate Mask" modal according to the Figma design file in the issue.

# Screenshot (if applicable)
Screenshot 2023-07-25 181312

# How to test

Go to accounts/profile, with premium features enabled. Then click the "Generate new mask" button.

# Checklist (Definition of Done)
- [x] Product Owner accepted the User Story (demo of functionality completed) or waived the privilege.
- [x] All acceptance criteria are met.
- [x] Jira ticket has been updated (if needed) to match changes made during the development process.
- [x] All UI revisions follow the [coding standards](https://github.com/mozilla/fx-private-relay/blob/main/docs/coding-standards.md), and use Protocol tokens where applicable (see `/frontend/src/styles/tokens.scss`).
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).
- [x] l10n changes have been submitted to the l10n repository, if any.

### CODE REVIEW

**Review by lloan — CHANGES_REQUESTED** [review]
I tested and this is what I see when I run the branch: 
image
 
I see `Enter email mask prefix` but it should be `Enter the text that goes before the @ symbol:` right? 

Code looks fine to me.

**Comment by rafeerahman** [comment]
> I tested and this is what I see when I run the branch: image
> 
> I see `Enter email mask prefix` but it should be `Enter the text that goes before the @ symbol:` right?
> 
> Code looks fine to me.

Oh, the variable storing `Enter the text that goes before the @ symbol:` (in pendingTranslations) is the same as `Enter email mask prefix` (old design). I think it prioritized locales, and extracted it from there instead of pendingTranslations. I deleted it in locales and replaced it with the new one, once that's merged should be good to go. I'll create that PR now.

**Comment by rafeerahman** [comment]
Waiting for L10 repo permissions before I merge to add the new strings.

**Comment by rafeerahman** [comment]
> @rafeerahman for the strings, do you have a link for the PR in that repository?

https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/153

**Comment by rafeerahman** [comment]
> I see `Enter email mask prefix` but it should be `Enter the text that goes before the @ symbol:` right?
> 
> Code looks fine to me.

I updated the pendingTranslations with new ID's now. Check again and you should see the new text

**Review by lloan — APPROVED** [review]
Looks good to me.

**Comment by rafeerahman** [comment]
Going to wait for https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/153 to get approved before I merge.

**Pull request merged**
