### PR TITLE
Update from Python 3.7 to 3.9

### LINKED ISSUE #1591: Update to Python 3.9
We're on Python 3.7, which is getting security updates until 2023-06-27. Python 3.9 was released 2020-10-05, is getting bugfix releases, and will be supported until 2025. Python 3.9 is supported by both our current Django 2.2.27 and our planned upgrade to 3.2 (#1586). We should update Python before Django.

References:
* [Python release schedule](https://www.python.org/downloads/), with maintenance dates
* [Django 3.2 release notes](https://docs.djangoproject.com/en/3.2/releases/3.2/): "Django 3.2 supports Python 3.6, 3.7, 3.8, 3.9, and 3.10 (as of 3.2.9)"
* [Django 2.2 release notes](https://docs.djangoproject.com/en/2.2/releases/2.2/): "Django 2.2 supports Python 3.5, 3.6, 3.7, 3.8 (as of 2.2.8), and 3.9 (as of 2.2.17)"

### PR DESCRIPTION
**Pull request by jwhitlock**
Update to Python 3.9.10 in the Dockerfile and Heroku. This PR fixes #1591

How to test:

- Use [pyenv](https://github.com/pyenv/pyenv) or similar to install Python 3.9.10, create a new virtual environment, and install the requirements
- Run tests in [developer mode](https://docs.python.org/3/library/devmode.html#devmode): ``python3.9 -X dev -m pytest``
- Run the server in developer mode, and poke around: ``python3.9 -X dev -m ./manage.py runserver``

There was a warning about unclosed files in `GetAttachmentTests`:

```
ResourceWarning: unclosed file <_io.BufferedRandom name=14>
```

This is fixed by closing the temporary attachment stream during test teardown.

**This leaves a few warnings that can be ignored for now**:

### pytest.yield_fixture warning

During test setup:

```
.../site-packages/pytest_django/fixtures.py:356: PytestDeprecationWarning: @pytest.yield_fixture is deprecated.
Use @pytest.fixture instead; they are the same.
```

This should be fixed by upgrading to [pytest-django 4.0.0](https://pytest-django.readthedocs.io/en/latest/changelog.html#v4-0-0-2020-10-16) or later, which support Python 3.9 and drops support for `pytest` before 5.4

### yaml.dump warning

Collected during test run:

```
api/tests/views_tests.py::test_swagger_format[yaml]
  .../site-packages/drf_yasg/codecs.py:202: PendingDeprecationWarning: 
  dump will be removed, use
  
    yaml=YAML(typ='unsafe', pure=True)
    yaml.dump(...)
  
  instead
    return yaml.dump(data, Dumper=SaneYamlDumper, default_flow_style=False, encoding='utf-8' if binary else None)

api/tests/views_tests.py::test_swagger_format[yaml]
  .../site-packages/ruamel/yaml/main.py:1364: PendingDeprecationWarning: 
  dump_all will be removed, use
  
    yaml=YAML(typ='unsafe', pure=True)
    yaml.dump_all(...)
  
  instead
    return dump_all(
```

This was filed upstream (https://github.com/axnsan12/drf-yasg/issues/765), but there has been no response in two months.

### Unclosed .env warning

When starting the development server:

```
.../site-packages/env_tools.py:48: ResourceWarning: unclosed file <_io.TextIOWrapper name='.env' mode='r' encoding='UTF-8'>
  env = '[root]\n' + io.open(filename, 'r').read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

This is included by [django-gulp](https://github.com/beaugunderson/django-gulp). There's no issue filed, but also the projects haven't been update for years...

### CODE REVIEW

**Comment by jwhitlock** [comment]
Rebased on main

**Review by groovecoder — APPROVED** [review]
Code looks good and spot-checks work: tests passed, and I spot-checked sending and receiving emails, replies, and with attachments too.

**Comment by jwhitlock** [comment]
@Vinnl - this turned out to be fairly easy, but it still may cause conflicts or merge issues with the React changes, so please review and merge on your schedule.

**Review by Vinnl — APPROVED** [review]
@jwhitlock React changes have already been merged in, and I don't see anything in here that should conflict with it, so feel free to merge! (And after the migration we can move away from Gulp, so that should resolve the `django-gulp` error as well.)

**Pull request merged**
